#!/bin/sh

BUNDLE_PATH=android/app/src/main/assets
BUNDLE_NAME=index.android.bundle
APK_PATH=android/app/build/outputs/apk

mkdir ${BUNDLE_PATH}

echo "
*******************************************
*                                         *
*              bundleAndroid              *
*                                         *
*******************************************
"

npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output ${BUNDLE_PATH}/${BUNDLE_NAME}

echo "
*******************************************
*                                         *
*             releaseAndroid              *
*                                         *
*******************************************
"
export ENVFILE=.env.prod
cd android
  ./gradlew assembleProdRelease
cd -

open ${APK_PATH}


